### ISSUE TITLE
Can't find '__main__' module in 'root/vf/arris...

### ISSUE THREAD

**Issue by lukasbonny** [fsck-block/arris-tg3442de-exporter#1]
Hey,
might be a dumb question, but your tool does not seem to work for me. Im not really good at python so it may be just a mistake from my side. I'm running Pyhton 3.9.2 on Debian 11. Any ideas maybe?
Thank you

**Comment by fsck-block** [comment]
Hi 
You are right. Following my own description doesn't succeed.
Please use the script `run.py` to start the exporter.

```sh-session
$ python3 run.py path/to/your/config.yml 
```
Please let me know if this works for you.

**Comment by lukasbonny** [comment]
Thanks for the quick reply. Unfornunatly I get this:

```
root@debian:~/vf/arris-tg3442de-exporter# sudo python3 run.py config.yml
Traceback (most recent call last):
  File "/root/vf/arris-tg3442de-exporter/run.py", line 6, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/vf/arris-tg3442de-exporter/tg3442de_exporter/tg3442de_exporter.py", line 172, in main
    config = load_config(config_file)
  File "/root/vf/arris-tg3442de-exporter/tg3442de_exporter/config.py", line 60, in load_config
    if config[EXPORTER][TIMEOUT_SECONDS] <= 0:
TypeError: 'NoneType' object is not subscriptable
```

I installed the requirements using pip install -r

**Comment by fsck-block** [comment]
Now it seem to be a problem of the `config.yml` file.
Is it possible for you to provide / post your file (without password)?

**Comment by lukasbonny** [comment]
Thanks a lot for your support.

```
# TG3442DE IP address
ip_address: 192.168.100.1

# TG3442DE web interface password
password: 

# All following parameters are optional.
exporter:
  # port on which this exporter exposes metrics (default: 9706)
  #port: 9706

  # filename to store call log
  # call_log_filename : 'tg3442de_call_log.json'

  # filename to store event log
  # event_log_filename : 'tg3442de_event_log.json'

  # timeout duration for connections to the TG3442DE (default: 9)
  #timeout_seconds: 9

  # Customize the family of metrics to scrape. By default, the 
  # log-metrics (call_log_local and event_log_local) are not scraped.
  #metrics: [device_status, docsis_status, overview_status, phone_status, call_log_local, event_log_local ]


```

This is the config.yml file. It is unchanged apart from the IP and the Password of course

**Comment by fsck-block** [comment]
Root cause identified, but i don't know if it's a bug or a feature.
When merging the default config and an empty user defined config the result is an empty config.
Used this code from ConnectBox Prometheus.
So the work around is to add an element to the user defined config. Even it is never used.
```
# TG3442DE IP address
ip_address: 192.168.0.1

# TG3442DE web interface password
password: WhatEverYourPasswordIs

# All following parameters are optional.
exporter:
  do_not_remove_this_line:

  # port on which this exporter exposes metrics (default: 9706)
  #port: 9706

  # filename to store call log
  # call_log_filename : 'tg3442de_call_log.json'

  # filename to store event log
  # event_log_filename : 'tg3442de_event_log.json'

  # timeout duration for connections to the TG3442DE (default: 9)
  #timeout_seconds: 9

  # Customize the family of metrics to scrape. By default, the 
  # log-metrics (call_log_local and event_log_local) are not scraped.
  #metrics: [device_status, docsis_status, overview_status, phone_status, call_log_local, event_log_local ]
```
Please let me know if this works for you.

**Comment by lukasbonny** [comment]
Awesome, works great now. Thank you so much for providing the project and your support!
